Repository geminabox/geminabox, pull requests merged in 2022-07, with the labels that each got.

#474 Drop support RubyGems 2.4.x
  .github/workflows/ruby.yml
  README.md
  geminabox.gemspec
Labels: Maintenance

#477 Move to normal for actions/stale only for issues
  .github/workflows/stale.yml
Labels: Maintenance

#476 Test setup changes
  .github/workflows/ruby.yml
  .gitignore
  Gemfile
  README.md
  test/requests/is_api_request_test.rb
  test/test_helper.rb
  test/test_support/gem_factory.rb
  test/test_support/geminabox_test_case.rb
  test/units/geminabox/server_test.rb
Labels: test

#480 Remove deprecated arguments for rake console
  Rakefile
Labels: Bug
