Repository geminabox/geminabox, pull requests merged in 2022-06, with the labels that each got.

#383 Pin multipart-post 2.1.x on Ruby 2.2 on CI
  Gemfile
Labels: Critical

#380 Use SVG format for Gemfury badge
  README.md
Labels: Support

#387 Bump actions/checkout from 2 to 3
  .github/workflows/ruby.yml
Labels: Maintenance

#388 Enable dependabot
  .github/dependabot.yml
Labels: Maintenance

#393 Unpin capybara-mechanize gem on CI
  Gemfile
Labels: Maintenance

#384 remove File.exists? deprecation warning
  lib/geminabox/proxy/copier.rb
  test/units/geminabox/proxy/copier_test.rb
Labels: Maintenance

#386 removed confusing backtrace from test output
  test/units/geminabox/proxy/copier_test.rb
Labels: Maintenance

#400 Revert "Merge pull request #361 from tnir/remove-jquery"
  public/jquery.js
  public/master.js
  views/index.erb
  views/layout.erb
Labels: Maintenance

#402 Update CI for 1.4 branch
  .github/workflows/ruby.yml
  README.md
Labels: Maintenance, test

#401 Release v1.4.3
  lib/geminabox/version.rb
Labels: Maintenance

#406 [1.4 port] Migrate Changelog entries for 1.0.0 and later to GitHub
  CHANGELOG.md
Labels: Support, Maintenance

#405 Migrate Changelog entries for 1.0.0 and later to GitHub
  CHANGELOG.md
Labels: Support, Maintenance

#407 Enable stale action for issues and PRs
  .github/workflows/stale.yml
Labels: Maintenance

#412 Update CI for 1.5 branch
  .github/workflows/ruby.yml
  README.md
Labels: Maintenance

#413 v1.5.0
  lib/geminabox/version.rb
Labels: Maintenance

#409 Add RuboCop 1.30.1 as linter
  .github/workflows/ruby.yml
  .rubocop.yml
  .rubocop_todo.yml
Labels: test

#417 Enable rubocop-minitest in RuboCop
  .github/workflows/ruby.yml
  .rubocop_todo.yml
Labels: Maintenance, test

#418 Enable rubocop-rake in RuboCop
  .github/workflows/ruby.yml
Labels: Maintenance, test

#356 remove has_rdoc from fixtures
  test/fixtures/geminabox-9999.0.0.gemspec
Labels: Maintenance

#420 Bump to 2.0.0.pre
  lib/geminabox/version.rb
Labels: Maintenance

#421 Build a pre-version gem and publish to Packages (for testing purpose only)
  .github/workflows/gem-push.yml
Labels: Maintenance, test

#357 Use a binary mode for file manipulations
  lib/geminabox/proxy/copier.rb
  lib/geminabox/proxy/file_handler.rb
  lib/geminabox/proxy/splicer.rb
  test/units/geminabox/incoming_gem_test.rb
  test/units/geminabox/proxy/splicer_test.rb
Labels: Maintenance

#419 Get rid of hardcoded paths
  lib/geminabox.rb
  lib/geminabox/server.rb
  test/integration/pushing_gems/data_dir_errors_test.rb
  test/test_helper.rb
  test/test_support/gem_factory.rb
  test/test_support/geminabox_test_case.rb
  test/units/geminabox/disk_cache_test.rb
Labels: Maintenance, test

#423 Drop RubyGems 1.8.24 and earlier
  .github/workflows/ruby.yml
  geminabox.gemspec
Labels: Maintenance, test

#364 Do not transform compressed files
  lib/geminabox/hostess.rb
  lib/geminabox/proxy/hostess.rb
Labels: Feature

#429 Remove patch for RubyGems 1.8.24 or earlier
  lib/geminabox/indexer.rb
  lib/geminabox/server.rb
Labels: Maintenance

#430 Remove a code branch for Ruby 1.8 and earlier
  lib/geminabox/incoming_gem.rb
Labels: Maintenance

#431 Prettier JavaScript files
  public/master.js
Labels: Maintenance

#432 Enable Prettier for JS files on Actions
  .github/workflows/prettier.yml
Labels: Maintenance, test

#433 Enable Prettier for CSS files on Actions
  .github/workflows/prettier.yml
  public/master.css
Labels: Maintenance

#436 Prepare 2.0.0.rc.1
  CHANGELOG.md
  lib/geminabox/version.rb
Labels: area/release-eng

#437 Release 2.0.0
  lib/geminabox/version.rb
Labels: area/release-eng

#438 Prepare 2.0.1
  lib/geminabox/version.rb
Labels: area/release-eng

#439 Move to normal for actions/stale only for PRs
  .github/workflows/stale.yml
Labels: Maintenance

#440 Simplify system requirements: Ruby and RubyGems
  README.md
Labels: Maintenance

#441 Prepare 2.1.0
  lib/geminabox/version.rb
Labels: area/release-eng

#428 Drop support RubyGems 2.3.x and earlier
  .github/workflows/ruby.yml
  geminabox.gemspec
Labels: Maintenance

#442 Remove IncomingGem code for RubyGems 1.x
  lib/geminabox/incoming_gem.rb
Labels: Maintenance

#444 Update system requirements with RubyGems 2.4 or higher
  README.md
Labels: Maintenance

#445 Update RuboCop from 1.30.1 to 1.31.0
  .github/workflows/ruby.yml
  .rubocop.yml
  .rubocop_todo.yml
Labels: Maintenance

#385 eliminate a faraday 1.x deprecation warning
  lib/geminabox/http_adapter/template_faraday_adapter.rb
Labels: Maintenance

#446 Limit sinatra dependency to 2.x by dropping 1.x
  geminabox.gemspec
Labels: Maintenance, security

#447 Allow admins to use Faraday v2 with Ruby 2.6+
  geminabox.gemspec
  lib/geminabox/http_adapter/template_faraday_adapter.rb
Labels: Maintenance, dependencies, ruby

#448 Move require rss from code to test
  Gemfile
  geminabox.gemspec
  lib/geminabox.rb
  test/requests/atom_feed_test.rb
Labels: Maintenance, dependencies, ruby, test

#454 Drop Ruby 2.2 support
  .github/workflows/ruby.yml
  .rubocop.yml
  README.md
  geminabox.gemspec
Labels: Maintenance

#455 Set TargetRubyVersion to 2.3 for RuboCop
  .rubocop.yml
  .rubocop_todo.yml
Labels: Maintenance

#456 Enable Bundler/OrderedGems cop
  .rubocop_todo.yml
  Gemfile
Labels: Maintenance

#457 Relax multipart-post gem used in tests
  Gemfile
Labels: Maintenance, test

#458 Drop Faraday v0 support
  geminabox.gemspec
  lib/geminabox/http_adapter/template_faraday_adapter.rb
Labels: Maintenance, dependencies, ruby

#459 Update gemspec to date
  geminabox.gemspec
Labels: Maintenance

#460 Prepare 2.1.0.rc.1
  lib/geminabox/version.rb
Labels: area/release-eng

#464 Prepare 2.2.0
  lib/geminabox/version.rb
Labels: area/release-eng

#468 Add Contributor Covenant Code of Conduct
  CODE_OF_CONDUCT.md
Labels: Maintenance

#469 Add CONTRIBUTING
  CONTRIBUTING.md
Labels: Maintenance

#471 Add setup guide for developers
  CONTRIBUTING.md
Labels: Maintenance
